/**
 * Renders every file of a generated hook project.
 *
 * The single source of truth for permissions is the `ResolvedPermissions` in the
 * context: the Solidity constant, the pool key `parameters` literal in the test,
 * the assertion in the deploy script and the README table are all derived from
 * it. There is no second place for them to disagree.
 */

import { CALLBACKS, renderCallback, renderImports, usedSymbols } from "./callbacks.js";
import { namesForBitmap, PERMISSION_OFFSETS, type ResolvedPermissions } from "../permissions.js";
import type { HookTemplate } from "../templates/index.js";

export interface ProjectPaths {
  /** POSIX relative path from the project root to `packages/core`, no trailing slash. */
  readonly core: string;
  /** POSIX relative path from the project root to `packages/hooks`, no trailing slash. */
  readonly hooks: string;
}

export interface ProjectContext {
  /** Directory name, e.g. `my-fee-hook`. */
  readonly projectName: string;
  /** Solidity contract name, e.g. `MyFeeHook`. */
  readonly contractName: string;
  readonly template: HookTemplate;
  readonly permissions: ResolvedPermissions;
  readonly tickSpacing: number;
  /** Static LP fee in hundredths of a bip, or `undefined` for a dynamic-fee pool. */
  readonly lpFee: number | undefined;
  /** The pool key `parameters` word, 0x-prefixed 32 bytes. */
  readonly parameters: string;
  readonly paths: ProjectPaths;
  /** False when the template's own bodies were dropped because a permission was deselected. */
  readonly templateApplies: boolean;
  readonly cliVersion: string;
}

const SOLC = "0.8.26";

function dir(path: string): string {
  return path.endsWith("/") ? path : `${path}/`;
}

/** Position range for the generated tests, snapped to the pool's tick spacing. */
export function tickRange(tickSpacing: number): { lower: number; upper: number } {
  const target = 6000;
  const multiples = Math.max(1, Math.floor(target / tickSpacing));
  const upper = multiples * tickSpacing;
  return { lower: -upper, upper };
}

// ---------------------------------------------------------------------------
// src/<Hook>.sol
// ---------------------------------------------------------------------------

export function renderHook(ctx: ProjectContext): string {
  const { template, permissions, contractName, templateApplies } = ctx;

  const types = new Set<string>(["ICLPoolManager"]);
  for (const type of templateApplies ? (template.types ?? []) : []) types.add(type);

  const bodies: string[] = [];
  for (const name of permissions.names) {
    const spec = CALLBACKS[name];
    if (spec === undefined) continue; // a *ReturnsDelta flag adds no function
    for (const type of spec.types) types.add(type);
    const impl = templateApplies ? template.implementations[name] : undefined;
    for (const type of impl?.types ?? []) types.add(type);
    bodies.push(renderCallback(spec, impl));
  }

  const extraArgs = templateApplies ? (template.constructorArgs ?? []) : [];
  const ctorParams = ["ICLPoolManager _poolManager", ...extraArgs.map((arg) => `${arg.type} ${arg.param}`)];
  const ctorAssignments = extraArgs.map((arg) => `        ${arg.name} = ${arg.param};`).join("\n");
  const ctorDoc = [
    "    /// @param _poolManager The CL pool manager permitted to call this hook",
    ...extraArgs.map((arg) => `    /// @param ${arg.param} ${arg.doc}`),
  ].join("\n");

  const permissionRows = permissions.names
    .map((name) => `///   bit ${String(PERMISSION_OFFSETS[name]).padStart(2)}  ${name}`)
    .join("\n");

  const doc = template.contractDoc.map((line) => `/// ${line}`).join("\n");

  const members = templateApplies && template.members !== undefined ? `${template.members}\n\n` : "";

  const ctorBody =
    ctorAssignments.length > 0
      ? ` {\n${ctorAssignments}\n    }`
      : " {}";

  // The contract body is assembled first so imports can be computed from what the
  // generated source actually mentions. Which types a body needs depends on the
  // template that supplied it, and an import of an unused name is a lint finding
  // in a project the developer has not written a line of yet.
  const body = `contract ${contractName} is BaseCLHook {
${members}${ctorDoc}
    constructor(${ctorParams.join(", ")}) BaseCLHook(_poolManager)${ctorBody}

    /// @inheritdoc BaseCLHook
    /// @dev Generated by create-latch-hook. Change this and you MUST change the
    /// \`parameters\` word of every pool key that points at this hook.
    function getHooksRegistrationBitmap() public pure override returns (uint16) {
        return ${permissions.solidityExpression};
    }

${bodies.join("\n\n")}
}
`;

  const imports = renderImports(["BaseCLHook", ...usedSymbols(types, body)]);

  return `// SPDX-License-Identifier: MIT
pragma solidity ${SOLC};

${imports}

/// @title ${contractName}
${doc}
///
/// @dev PERMISSIONS. This hook registers ${permissions.bitmapHex}:
${permissionRows.length > 0 ? permissionRows : "///   (none)"}
///
/// That same value must appear in the low 16 bits of every pool key that uses this
/// hook, or \`Hooks.validateHookConfig\` reverts with \`HookConfigValidationError\` when
/// the pool is initialized. The matching \`parameters\` word for tick spacing
/// ${ctx.tickSpacing} is:
///
///   ${ctx.parameters}
///
/// Unlike Uniswap v4, this hook's ADDRESS carries no meaning. Permissions live in the
/// pool key, so there is no CREATE2 salt to mine and the same deployed hook can be
/// redeployed anywhere without changing a thing.
${body}`;
}

// ---------------------------------------------------------------------------
// test/<Hook>.t.sol
// ---------------------------------------------------------------------------

export function renderTest(ctx: ProjectContext): string {
  const { contractName, permissions, template, templateApplies } = ctx;
  const range = tickRange(ctx.tickSpacing);

  const extraArgs = templateApplies ? (template.constructorArgs ?? []) : [];
  const ctorCall = ["poolManager", ...extraArgs.map((arg) => arg.testValue)].join(", ");

  const feeExpression =
    ctx.lpFee === undefined ? "LPFeeLibrary.DYNAMIC_FEE_FLAG" : `uint24(${ctx.lpFee})`;

  const extraImports = new Set<string>(templateApplies ? (template.testImports ?? []) : []);
  if (ctx.lpFee === undefined) extraImports.add("LPFeeLibrary");
  const importBlock = renderImports(extraImports);

  const extraTests =
    templateApplies && template.extraTests !== undefined ? `\n\n${template.extraTests(contractName)}` : "";

  const enabled = namesForBitmap(permissions.bitmap);
  const enabledComment = enabled.length === 0 ? "no callbacks" : enabled.join(", ");

  return `// SPDX-License-Identifier: MIT
pragma solidity ${SOLC};

import {Test} from "forge-std/Test.sol";

import {Vault} from "infinity-core/src/Vault.sol";
import {CLPoolManager} from "infinity-core/src/pool-cl/CLPoolManager.sol";
import {ICLPoolManager} from "infinity-core/src/pool-cl/interfaces/ICLPoolManager.sol";
import {IPoolManager} from "infinity-core/src/interfaces/IPoolManager.sol";
import {IHooks} from "infinity-core/src/interfaces/IHooks.sol";
import {Hooks} from "infinity-core/src/libraries/Hooks.sol";
import {PoolKey} from "infinity-core/src/types/PoolKey.sol";
import {Currency} from "infinity-core/src/types/Currency.sol";
import {BalanceDelta} from "infinity-core/src/types/BalanceDelta.sol";
import {CLPoolParametersHelper} from "infinity-core/src/pool-cl/libraries/CLPoolParametersHelper.sol";
import {TickMath} from "infinity-core/src/pool-cl/libraries/TickMath.sol";
import {CLPoolManagerRouter} from "infinity-core/test/pool-cl/helpers/CLPoolManagerRouter.sol";
import {MockERC20} from "solmate/src/test/utils/mocks/MockERC20.sol";
${importBlock.length > 0 ? `${importBlock}\n` : ""}
import {${contractName}} from "../src/${contractName}.sol";

/// @title ${contractName}Test
/// @notice Deploys the whole settlement stack in memory - Vault, CLPoolManager, a
/// router and two mock tokens - initializes a pool that registers ${contractName},
/// and exercises it end to end.
contract ${contractName}Test is Test {
    /*//////////////////////////////////////////////////////////////
        The two values that must never disagree.

        EXPECTED_BITMAP is what the hook reports from
        getHooksRegistrationBitmap(); EXPECTED_PARAMETERS is the pool key word
        that carries it, alongside the tick spacing. \`Hooks.validateHookConfig\`
        compares them at initialize() and reverts on a mismatch.

        Both were generated together by create-latch-hook. Enabled callbacks:
        ${enabledComment}
    //////////////////////////////////////////////////////////////*/

    uint16 internal constant EXPECTED_BITMAP = ${permissions.bitmapHex};
    // forge-lint: disable-next-line(too-many-digits)
    bytes32 internal constant EXPECTED_PARAMETERS = ${ctx.parameters};

    int24 internal constant TICK_SPACING = ${ctx.tickSpacing};
    int24 internal constant TICK_LOWER = ${range.lower};
    int24 internal constant TICK_UPPER = ${range.upper};
    uint24 internal constant LP_FEE = ${feeExpression};

    /// @dev sqrt(1) in Q64.96, i.e. a 1:1 starting price
    uint160 internal constant SQRT_PRICE_1_1 = 79_228_162_514_264_337_593_543_950_336;

    uint8 internal constant TOKEN_DECIMALS = 18;
    uint256 internal constant STARTING_BALANCE = 1_000_000 ether;
    int256 internal constant LIQUIDITY_DELTA = 100_000 ether;

    /// @dev Negative amounts are exact-input swaps.
    int256 internal constant SWAP_AMOUNT = -1 ether;
    int256 internal constant SMALL_SWAP_AMOUNT = -0.1 ether;

    Vault internal vault;
    CLPoolManager internal poolManager;
    CLPoolManagerRouter internal router;
    MockERC20 internal token0;
    MockERC20 internal token1;
    ${contractName} internal hook;
    PoolKey internal key;

    function setUp() public {
        vault = new Vault();
        poolManager = new CLPoolManager(vault);

        // The pool manager moves funds on the Vault's books, so it has to be
        // registered. registerApp is irreversible on a real deployment.
        vault.registerApp(address(poolManager));

        router = new CLPoolManagerRouter(vault, poolManager);

        MockERC20 tokenA = new MockERC20("Latch Test Token A", "LTA", TOKEN_DECIMALS);
        MockERC20 tokenB = new MockERC20("Latch Test Token B", "LTB", TOKEN_DECIMALS);
        (token0, token1) =
            address(tokenA) < address(tokenB) ? (tokenA, tokenB) : (tokenB, tokenA);

        token0.mint(address(this), STARTING_BALANCE);
        token1.mint(address(this), STARTING_BALANCE);
        require(token0.approve(address(router), type(uint256).max), "token0 approval rejected");
        require(token1.approve(address(router), type(uint256).max), "token1 approval rejected");

        hook = new ${contractName}(${ctorCall});

        key = _keyWithHook(address(hook));
        _initialize(key);
        _addLiquidity(key);
    }

    /*//////////////////////////////////////////////////////////////
                        THE CONFIGURATION INVARIANT
    //////////////////////////////////////////////////////////////*/

    /// @notice The hook's own bitmap, the pool key's bitmap and the generated
    /// constant are the same number.
    /// @dev If you add a callback to the hook and forget the pool key (or the other
    /// way round), this test fails here instead of your users' swaps failing later.
    function test_registrationBitmapMatchesPoolKey() public view {
        assertEq(hook.getHooksRegistrationBitmap(), EXPECTED_BITMAP, "hook bitmap drifted");
        assertEq(uint16(uint256(key.parameters)), EXPECTED_BITMAP, "pool key bitmap drifted");
        assertEq(CLPoolParametersHelper.getTickSpacing(key.parameters), TICK_SPACING, "tick spacing drifted");
    }

    /// @notice A pool key whose bitmap does not match the hook cannot be created.
    /// @dev This is the failure new hook developers hit most often. Reproduced here so
    /// the error - HookConfigValidationError - is one you have already seen.
    function test_mismatchedBitmapRevertsAtInitialize() public {
        PoolKey memory mismatched = _keyWithHook(address(hook));
        mismatched.parameters = bytes32(uint256(EXPECTED_PARAMETERS) ^ 1); // flip bit 0

        vm.expectRevert(Hooks.HookConfigValidationError.selector);
        // forge-lint: disable-next-line(unused-return)
        poolManager.initialize(mismatched, SQRT_PRICE_1_1);
    }

    /// @notice The hook works from an address with no special bits at all.
    /// @dev This is the part Uniswap v4 cannot do. There, a hook's permissions are read
    /// from its address, so shipping one means grinding a CREATE2 salt until the deployed
    /// address happens to carry the right low bits - and any change to the permission set
    /// means grinding again. Latch reads permissions from the pool key, so the same code
    /// works at 0x...dead as it does anywhere else.
    function test_hookWorksFromAnArbitraryAddress() public {
        address arbitrary = address(0xDEAD);
        vm.etch(arbitrary, address(hook).code);

        PoolKey memory otherKey = _keyWithHook(arbitrary);
        _initialize(otherKey);
        _addLiquidity(otherKey);

        BalanceDelta delta = _swap(otherKey, true, SMALL_SWAP_AMOUNT);
        assertLt(delta.amount0(), 0, "swap did not spend token0");
        assertGt(delta.amount1(), 0, "swap did not return token1");
    }

    /*//////////////////////////////////////////////////////////////
                              BEHAVIOUR
    //////////////////////////////////////////////////////////////*/

    /// @notice The pool is live: liquidity is in range and swaps execute.
    function test_poolAcceptsLiquidityAndSwaps() public {
        assertGt(poolManager.getLiquidity(key.toId()), 0, "no liquidity in range");

        BalanceDelta delta = _swap(key, true, SWAP_AMOUNT);
        assertEq(delta.amount0(), SWAP_AMOUNT, "exact input was not consumed exactly");
        assertGt(delta.amount1(), 0, "swap returned nothing");
    }

    /// @notice Swapping the other way round works too.
    function test_swapOneForZero() public {
        BalanceDelta delta = _swap(key, false, SWAP_AMOUNT);
        assertEq(delta.amount1(), SWAP_AMOUNT, "exact input was not consumed exactly");
        assertGt(delta.amount0(), 0, "swap returned nothing");
    }${extraTests}

    /*//////////////////////////////////////////////////////////////
                               HELPERS
    //////////////////////////////////////////////////////////////*/

    function _keyWithHook(address hookAddress) internal view returns (PoolKey memory) {
        return PoolKey({
            currency0: Currency.wrap(address(token0)),
            currency1: Currency.wrap(address(token1)),
            hooks: IHooks(hookAddress),
            poolManager: IPoolManager(address(poolManager)),
            fee: LP_FEE,
            parameters: EXPECTED_PARAMETERS
        });
    }

    function _initialize(PoolKey memory poolKey) internal {
        int24 tick = poolManager.initialize(poolKey, SQRT_PRICE_1_1);
        assertEq(tick, int24(0), "pool did not start at the 1:1 tick");
    }

    function _addLiquidity(PoolKey memory poolKey) internal {
        ICLPoolManager.ModifyLiquidityParams memory params = ICLPoolManager.ModifyLiquidityParams({
            tickLower: TICK_LOWER,
            tickUpper: TICK_UPPER,
            liquidityDelta: LIQUIDITY_DELTA,
            salt: bytes32(0)
        });

        (BalanceDelta delta, BalanceDelta feeDelta) = router.modifyPosition(poolKey, params, "");

        assertLt(delta.amount0(), 0, "adding liquidity cost no token0");
        assertLt(delta.amount1(), 0, "adding liquidity cost no token1");
        assertEq(BalanceDelta.unwrap(feeDelta), int256(0), "a fresh position cannot have accrued fees");
    }

    function _swap(PoolKey memory poolKey, bool zeroForOne, int256 amountSpecified)
        internal
        returns (BalanceDelta)
    {
        ICLPoolManager.SwapParams memory params = ICLPoolManager.SwapParams({
            zeroForOne: zeroForOne,
            amountSpecified: amountSpecified,
            sqrtPriceLimitX96: zeroForOne ? TickMath.MIN_SQRT_RATIO + 1 : TickMath.MAX_SQRT_RATIO - 1
        });
        CLPoolManagerRouter.SwapTestSettings memory settings =
            CLPoolManagerRouter.SwapTestSettings({withdrawTokens: true, settleUsingTransfer: true});

        return router.swap(poolKey, params, settings, "");
    }
}
`;
}

// ---------------------------------------------------------------------------
// script/Deploy<Hook>.s.sol
// ---------------------------------------------------------------------------

export function renderDeployScript(ctx: ProjectContext): string {
  const { contractName, permissions, template, templateApplies } = ctx;
  const extraArgs = templateApplies ? (template.constructorArgs ?? []) : [];
  const ctorArgs = ["ICLPoolManager(clPoolManager)", ...extraArgs.map((arg) => arg.deployExpr)].join(", ");

  const feeLine =
    ctx.lpFee === undefined
      ? '        console.log("pool fee            : dynamic (LPFeeLibrary.DYNAMIC_FEE_FLAG, 0x800000)");'
      : `        console.log("pool fee            : ${ctx.lpFee} (${(ctx.lpFee / 10_000).toFixed(4)}%)");`;

  return `// SPDX-License-Identifier: MIT
pragma solidity ${SOLC};

import {Script} from "forge-std/Script.sol";
import {console} from "forge-std/console.sol";

import {ICLPoolManager} from "infinity-core/src/pool-cl/interfaces/ICLPoolManager.sol";
import {CLPoolParametersHelper} from "infinity-core/src/pool-cl/libraries/CLPoolParametersHelper.sol";

import {${contractName}} from "../src/${contractName}.sol";

/// @title Deploy${contractName}
/// @notice Deploys the hook and prints the exact \`parameters\` word its pools need.
///
/// @dev Usage against a local devnet started with \`latch devnet\`:
///
///   forge script script/Deploy${contractName}.s.sol:Deploy${contractName} \\
///       --rpc-url http://127.0.0.1:8545 --broadcast
///
/// Environment:
///   PRIVATE_KEY       deployer key (the devnet prints one)
///   CL_POOL_MANAGER   address of CLPoolManager (the devnet prints it)
///   TICK_SPACING      optional, defaults to ${ctx.tickSpacing}
contract Deploy${contractName} is Script {
    /// @dev Generated alongside the hook's getHooksRegistrationBitmap(). The
    /// assertion below is what keeps the two honest at deploy time.
    uint16 internal constant EXPECTED_BITMAP = ${permissions.bitmapHex};

    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        address clPoolManager = vm.envAddress("CL_POOL_MANAGER");
        int256 rawTickSpacing = vm.envOr("TICK_SPACING", int256(${ctx.tickSpacing}));
        require(
            rawTickSpacing >= 1 && rawTickSpacing <= int256(type(int16).max),
            "TICK_SPACING outside CLPoolManager's MIN/MAX_TICK_SPACING"
        );
        // forge-lint: disable-next-line(unsafe-typecast)
        int24 tickSpacing = int24(rawTickSpacing);

        vm.startBroadcast(deployerPrivateKey);
        ${contractName} hook = new ${contractName}(${ctorArgs});
        vm.stopBroadcast();

        uint16 onChainBitmap = hook.getHooksRegistrationBitmap();
        require(onChainBitmap == EXPECTED_BITMAP, "bitmap drifted from the generated constant");

        bytes32 parameters =
            CLPoolParametersHelper.setTickSpacing(bytes32(uint256(onChainBitmap)), tickSpacing);

        console.log("");
        console.log("=== ${contractName} deployed ===");
        console.log("hook                :", address(hook));
        console.log("registration bitmap :", vm.toString(onChainBitmap));
        console.log("pool key parameters :", vm.toString(parameters));
${feeLine}
        console.log("");
        console.log("Use that parameters word verbatim in your PoolKey. Any other value");
        console.log("makes CLPoolManager.initialize revert with HookConfigValidationError.");
    }
}
`;
}

// ---------------------------------------------------------------------------
// foundry.toml
// ---------------------------------------------------------------------------

export function renderFoundryToml(ctx: ProjectContext): string {
  const core = dir(ctx.paths.core);
  const hooks = dir(ctx.paths.hooks);

  const shared = (transient: string) => `remappings = [
    "infinity-core/=${core}",
    "latch-hooks/=${hooks}",
    "forge-std/=${core}lib/forge-std/src/",
    "ds-test/=${core}lib/forge-std/lib/ds-test/src/",
    "@openzeppelin/=${core}lib/openzeppelin-contracts/",
    "solmate/=${core}lib/solmate/",
    "${transient}",
]`;

  return `# Generated by create-latch-hook ${ctx.cliVersion}.
#
# Two build profiles, one source tree. They differ only in the transient-storage
# backend Latch's settlement layer is compiled against:
#
#   forge build                          # default: EIP-1153 (tstore/tload), cancun
#   FOUNDRY_PROFILE=legacy forge build   # legacy:  SSTORE/SLOAD,            shanghai
#
# Pick "legacy" only for chains without EIP-1153. Anvil is Cancun-capable, so the
# default profile is the right one locally.
#
# The "hp-transient/" remapping is pinned here, per profile, and deliberately NOT
# in a remappings.txt: that file silently overrides per-profile remappings and
# would build the wrong backend under --profile legacy.

[profile.default]
src = "src"
test = "test"
script = "script"
out = "foundry-out"
libs = []
solc_version = "${SOLC}"
optimizer_runs = 25_666
via_ir = true
evm_version = "cancun"
bytecode_hash = "none"
allow_paths = ["${ctx.paths.core}", "${ctx.paths.hooks}"]
allow_internal_expect_revert = true
${shared(`hp-transient/=${core}src/libraries/transient/eip1153/`)}

[profile.legacy]
src = "src"
test = "test"
script = "script"
out = "foundry-out-legacy"
libs = []
solc_version = "${SOLC}"
optimizer_runs = 25_666
via_ir = true
evm_version = "shanghai"
bytecode_hash = "none"
allow_paths = ["${ctx.paths.core}", "${ctx.paths.hooks}"]
allow_internal_expect_revert = true
${shared(`hp-transient/=${core}src/libraries/transient/storage/`)}

[fuzz]
runs = 256
`;
}

// ---------------------------------------------------------------------------
// latch.json - machine-readable record of what was generated
// ---------------------------------------------------------------------------

export function renderLatchConfig(ctx: ProjectContext): string {
  return `${JSON.stringify(
    {
      $schema: "https://latchprotocol.dev/schema/hook-project.json",
      generatedBy: `create-latch-hook@${ctx.cliVersion}`,
      poolType: "CL",
      contract: ctx.contractName,
      template: ctx.template.id,
      permissions: {
        names: ctx.permissions.names,
        bitmap: ctx.permissions.bitmap,
        bitmapHex: ctx.permissions.bitmapHex,
      },
      poolKey: {
        parameters: ctx.parameters,
        tickSpacing: ctx.tickSpacing,
        fee: ctx.lpFee ?? "dynamic",
      },
    },
    null,
    2,
  )}\n`;
}

// ---------------------------------------------------------------------------
// README.md
// ---------------------------------------------------------------------------

export function renderReadme(ctx: ProjectContext): string {
  const { contractName, permissions, template, projectName } = ctx;

  const permissionTable = [
    "| bit | callback | implemented in |",
    "| --: | -------- | -------------- |",
    ...permissions.names.map((name) => {
      const spec = CALLBACKS[name];
      const where =
        spec === undefined ? "_flag only - enables a return value on another callback_" : `\`${spec.fn}\``;
      return `| ${PERMISSION_OFFSETS[name]} | \`${name}\` | ${where} |`;
    }),
  ].join("\n");

  const dependencyNote =
    permissions.addedDependencies.length === 0
      ? ""
      : `\n> Added automatically because a \`*ReturnsDelta\` flag requires it: ${permissions.addedDependencies
          .map((name) => `\`${name}\``)
          .join(", ")}.\n`;

  const feeText =
    ctx.lpFee === undefined
      ? "`LPFeeLibrary.DYNAMIC_FEE_FLAG` (0x800000) - the hook supplies the fee on every swap"
      : `\`${ctx.lpFee}\` (${(ctx.lpFee / 10_000).toFixed(2)}%), static`;

  const notes = template.readmeNotes.map((note) => `- ${note}`).join("\n");

  return `# ${projectName}

A [Latch Protocol](https://github.com/latchprotocol) concentrated-liquidity hook,
generated by \`create-latch-hook\` from the \`${template.id}\` template.

${template.description.charAt(0).toUpperCase()}${template.description.slice(1)}.

## Quickstart

\`\`\`bash
forge build
forge test -vv
\`\`\`

That is the whole loop. No CREATE2 salt to mine, no address to grind: on Latch a
hook's permissions live in the pool key, not in the hook's address, so
\`${contractName}\` works from wherever it happens to be deployed.

To try it against a local node:

\`\`\`bash
latch devnet                      # in another terminal; prints CL_POOL_MANAGER and a key

export PRIVATE_KEY=0x...          # PowerShell: $env:PRIVATE_KEY = "0x..."
export CL_POOL_MANAGER=0x...
forge script script/Deploy${contractName}.s.sol:Deploy${contractName} \\
    --rpc-url http://127.0.0.1:8545 --broadcast
\`\`\`

## The one thing that must not drift

\`\`\`
registration bitmap   ${permissions.bitmapHex}
pool key parameters   ${ctx.parameters}
tick spacing          ${ctx.tickSpacing}
pool fee              ${feeText}
\`\`\`

\`CLPoolManager.initialize\` reads the low 16 bits of \`poolKey.parameters\` and
compares them with what the hook returns from \`getHooksRegistrationBitmap()\`
(\`Hooks.validateHookConfig\`). If they differ, pool creation reverts with
\`HookConfigValidationError\` - it is the most common way a first hook fails.

Both values above were generated together, and
\`test_registrationBitmapMatchesPoolKey\` fails the build if they ever stop
agreeing. If you add or remove a callback, change **both**: the expression in
\`getHooksRegistrationBitmap()\` and the \`EXPECTED_PARAMETERS\` constant in the
test. The deploy script re-derives \`parameters\` from the hook itself, so it can
never print a stale one.

### Registered callbacks
${dependencyNote}
${permissionTable}

## Layout

\`\`\`
src/${contractName}.sol             the hook
test/${contractName}.t.sol          Vault + CLPoolManager + router, end to end
script/Deploy${contractName}.s.sol  deploys and prints the pool key parameters
foundry.toml                        remappings and the two build profiles
latch.json                          machine-readable record of the above
\`\`\`

## Notes for this template

${notes.length > 0 ? notes : "- Nothing template-specific; this is a plain starting point."}

## Build profiles

Latch targets chains on both sides of the Cancun upgrade, so the settlement layer
compiles against one of two API-identical transient-storage backends:

\`\`\`bash
forge test                          # EIP-1153 (tstore/tload), evm_version = cancun
FOUNDRY_PROFILE=legacy forge test   # SSTORE/SLOAD,            evm_version = shanghai
\`\`\`

Use \`legacy\` only when deploying to a chain without EIP-1153. Anvil is
Cancun-capable, so local work uses the default profile.

## Security checklist before you ship

- Every callback is \`onlyPoolManager\` via \`BaseCLHook\`. Do not add an external
  state-mutating function that assumes it can only be reached from a callback.
- A reverting \`beforeSwap\` makes the pool untradeable for as long as the
  condition holds. That is a feature for a launch gate and a denial-of-service
  bug everywhere else.
- Declaring a permission you have not implemented is not a silent no-op:
  \`BaseCLHook\`'s default override points revert with \`HookNotImplemented\`.
- \`*ReturnsDelta\` permissions let the hook move user funds. They are bounded by
  \`HookDeltaExceedsSwapAmount\`, and by nothing else.
`;
}

export function renderGitignore(): string {
  return `foundry-out/
foundry-out-legacy/
cache/
broadcast/
out/
.env
node_modules/
`;
}
