// SPDX-License-Identifier: MIT
/**
 * Development harness.
 *
 * Renders all three widgets against the mock adapter, with controls for the
 * things that are hard to reach otherwise: the integrator fee, the theme, the
 * narrow-sidebar width, artificial latency and a wallet that rejects.
 *
 * Nothing here is a demo of the protocol. It is a demo of the widgets, running
 * on fabricated data, and it says so on every screen.
 */

import { StrictMode, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import {
  createMockAdapter,
  IntegratorConfigError,
  LaunchWidget,
  LiquidityWidget,
  MAX_INTEGRATOR_FEE_BPS,
  SwapWidget,
  WidgetProvider,
  type ChainConfig,
  type IntegratorConfig,
  type WidgetTheme,
} from "../src/index.js";
import { defineLatchWidgets } from "../src/embed.js";

defineLatchWidgets();

/**
 * A fictional chain config.
 *
 * These addresses are not deployments. They are placeholders that exist so the
 * config validator has something well-formed to accept.
 */
const DEMO_CHAIN: ChainConfig = {
  chainId: 31337,
  name: "Local mock chain (no deployment)",
  nativeCurrency: { name: "Mock gas token", symbol: "MOCK-GAS", decimals: 18 },
  contracts: {
    vault: "0x00000000000000000000000000000000000000a1",
    clPoolManager: "0x00000000000000000000000000000000000000a2",
    binPoolManager: "0x00000000000000000000000000000000000000a3",
    universalRouter: "0x00000000000000000000000000000000000000a4",
    clPositionManager: "0x00000000000000000000000000000000000000a5",
    binPositionManager: "0x00000000000000000000000000000000000000a6",
    permit2: "0x000000000022D473030F116dDEE9F6B43aC78BA3",
    launchGuardHook: "0x00000000000000000000000000000000000000a7",
  },
  defaultDeadlineSeconds: 20 * 60,
};

const DEMO_ACCOUNT = "0x00000000000000000000000000000000000000ff" as const;
const DEMO_REFERRER = "0x1111111111111111111111111111111111111111" as const;

function Harness(): JSX.Element {
  const [theme, setTheme] = useState<WidgetTheme>("system");
  const [feeBps, setFeeBps] = useState(25);
  const [referrer, setReferrer] = useState<string>(DEMO_REFERRER);
  const [connected, setConnected] = useState(true);
  const [latencyMs, setLatencyMs] = useState(250);
  const [rejectTransactions, setRejectTransactions] = useState(false);
  const [narrow, setNarrow] = useState(false);

  const adapter = useMemo(
    () =>
      createMockAdapter({
        chain: DEMO_CHAIN,
        account: connected ? DEMO_ACCOUNT : null,
        latencyMs,
        rejectTransactions,
      }),
    [connected, latencyMs, rejectTransactions],
  );

  const integrator: IntegratorConfig = useMemo(
    () => ({ referrer: referrer as `0x${string}`, feeBps }),
    [referrer, feeBps],
  );

  // Validate here rather than letting the provider throw, so the harness can
  // demonstrate the failure instead of blanking the page.
  let configError: string | null = null;
  try {
    if (feeBps > 0 && !/^0x[0-9a-fA-F]{40}$/.test(referrer)) {
      throw new IntegratorConfigError(
        "REFERRER_MALFORMED",
        `referrer is not a valid EVM address: ${JSON.stringify(referrer)}`,
      );
    }
  } catch (cause: unknown) {
    configError = cause instanceof Error ? cause.message : String(cause);
  }

  return (
    <main>
      <div className="banner" role="note">
        Mock data — nothing here is live
        <p>
          No Latch Protocol contracts are deployed and there is no RPC endpoint.
          Every price, balance, route, position and sale below is generated by
          the development mock adapter. Do not read any number on this page as a
          market price.
        </p>
      </div>

      <h1>Latch Protocol widgets — development harness</h1>
      <p className="lede">
        All three widgets, rendered against the mock adapter. Change the
        integrator fee below and watch it appear in the swap summary and in the
        transaction the widget prepares — that path is the whole point of the
        package.
      </p>

      <div className="controls">
        <label>
          Theme
          <select
            value={theme}
            onChange={(event) => setTheme(event.target.value as WidgetTheme)}
          >
            <option value="system">system</option>
            <option value="light">light</option>
            <option value="dark">dark</option>
          </select>
        </label>

        <label>
          Integrator fee (bps, max {MAX_INTEGRATOR_FEE_BPS})
          <input
            type="number"
            min={0}
            max={MAX_INTEGRATOR_FEE_BPS}
            value={feeBps}
            onChange={(event) => setFeeBps(Number(event.target.value))}
          />
        </label>

        <label style={{ minWidth: 340 }}>
          Referrer address
          <input
            type="text"
            value={referrer}
            onChange={(event) => setReferrer(event.target.value)}
          />
        </label>

        <label>
          Mock latency (ms)
          <input
            type="number"
            min={0}
            max={3000}
            step={50}
            value={latencyMs}
            onChange={(event) => setLatencyMs(Number(event.target.value))}
          />
        </label>

        <label>
          Wallet connected
          <input
            type="checkbox"
            checked={connected}
            onChange={(event) => setConnected(event.target.checked)}
          />
        </label>

        <label>
          Wallet rejects
          <input
            type="checkbox"
            checked={rejectTransactions}
            onChange={(event) => setRejectTransactions(event.target.checked)}
          />
        </label>

        <label>
          360px sidebar
          <input
            type="checkbox"
            checked={narrow}
            onChange={(event) => setNarrow(event.target.checked)}
          />
        </label>
      </div>

      {configError !== null ? (
        <pre role="alert" style={{ borderColor: "#b42318", color: "#b42318" }}>
          {configError}
        </pre>
      ) : null}

      <WidgetProvider adapter={adapter} integrator={integrator} theme={theme}>
        <div className="grid">
          <section className="cell">
            <h2>Swap</h2>
            <div className={narrow ? "narrow" : undefined}>
              <SwapWidget />
            </div>
            <p className="note">
              With a fee configured, the summary shows the integrator line and
              the minimum received is the post-fee floor.
            </p>
          </section>

          <section className="cell">
            <h2>Liquidity (CL and bin)</h2>
            <div className={narrow ? "narrow" : undefined}>
              <LiquidityWidget />
            </div>
            <p className="note">
              Switch pools to move between a tick range and a bin range. The
              widget above the range editor is identical for both.
            </p>
          </section>

          <section className="cell">
            <h2>Launch</h2>
            <div className={narrow ? "narrow" : undefined}>
              <LaunchWidget />
            </div>
            <p className="note">
              A launch is a pool with LaunchGuardHook attached and a decaying LP
              fee. The mock advances one block per second, so the schedule moves
              from &ldquo;not open&rdquo; through the decay to a settled fee
              while you watch.
            </p>
          </section>
        </div>
      </WidgetProvider>

      <section style={{ marginTop: 40 }}>
        <h2 style={{ fontSize: 14, textTransform: "uppercase", letterSpacing: "0.06em" }}>
          Custom element (no React in the host)
        </h2>
        <p className="note" style={{ maxWidth: "70ch" }}>
          The same swap widget, rendered through <code>&lt;latch-swap-widget&gt;</code>{" "}
          into a shadow root. This is the path a Vue, Svelte or plain-HTML host
          takes.
        </p>
        <div className={narrow ? "narrow" : undefined} style={{ marginTop: 12 }}>
          <latch-swap-widget
            adapter="mock"
            account={connected ? DEMO_ACCOUNT : undefined}
            theme={theme}
            title-text="Swap (web component)"
            integrator={JSON.stringify({ referrer, feeBps })}
            chain={JSON.stringify(DEMO_CHAIN)}
          />
        </div>
      </section>
    </main>
  );
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "latch-swap-widget": {
        adapter?: string;
        account?: string | undefined;
        theme?: string;
        "title-text"?: string;
        integrator?: string;
        chain?: string;
      };
    }
  }
}

const container = document.getElementById("root");
if (container === null) throw new Error("demo: #root is missing from index.html");

createRoot(container).render(
  <StrictMode>
    <Harness />
  </StrictMode>,
);
