// Extracts the ABIs the web app reads from the compiled Foundry artifacts.
// Hand-written ABIs drift silently the moment a contract changes — that already
// happened once in apps/api and was only caught by a diff test. Generate instead.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = resolve(here, '../../..')
const out = resolve(here, '../src/lib/abi')
mkdirSync(out, { recursive: true })

const SOURCES = [
  ['registry', 'packages/registry/foundry-out/LatchHookRegistry.sol/LatchHookRegistry.json'],
]

for (const [name, rel] of SOURCES) {
  const p = resolve(repo, rel)
  const { abi } = JSON.parse(readFileSync(p, 'utf8'))
  writeFileSync(
    resolve(out, `${name}.ts`),
    `// GENERATED by scripts/sync-abi.mjs from ${rel} — do not edit.\n` +
      `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const\n`,
  )
  console.log(`[sync-abi] ${name}: ${abi.length} entries`)
}
