/* ============================================================================
   /app/marketplace/:address — one Latch, in full.

   The marketplace shows cards; this is the product page behind a card. It is
   the in-app counterpart of the public `/verify/:hookAddress` permalink and
   reads through the same `readRegisteredLatch`, so the two can never disagree
   about whether a Latch is registered.

   The page is ordered the way a decision is actually made, which is close to
   the reverse of how a store usually sells something:

     1. Who it is, the info strip of on-chain signals, and any warning it has
        earned — on the hero, above everything the submitter wrote.
     2. What it CAN DO — the three-question ledger and all fourteen permission
        bits as named, inspectable cells, decoded from its own bytecode and
        grouped by what each callback is able to do. This is the section nobody
        can fake and it is the one that gets the most page.
     3. Only then, what the submitter says about it, marked as their words.
     4. The information table: every address and link, each marked as either
        read from chain or claimed by the submitter.

   The same rule the verify page is built around applies here and is the reason
   both use `readRegisteredLatch` rather than reading the record directly: an
   address the registry has never heard of must NOT render as a listed Latch
   with empty fields. "Unverified · Passive · Active" is the most reassuring
   thing that could be said about a contract, and a zeroed struct says all
   three. So `found: false` is a different screen, not a sparse version of this
   one.

   Naming note: the URL and the copy say Latch, because that is the product.
   The contract-level names stay as they are — `LatchRegistry`,
   `getHooksRegistrationBitmap()` — because that is what the chain actually
   exposes, and renaming them in the UI would misdescribe the API a developer
   has to call.
   ============================================================================ */

import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'

import { ChainTag, chainNameFor } from '../../../components/ChainTag.tsx'
import {
  HOOK_CALLBACK_BIT,
  PERM,
  type HookCallback,
} from '../../../data/registry.generated.ts'
import {
  DEPLOYMENTS,
  ACTIVE_CHAIN_ID,
  explorerAddress,
  readRegisteredLatch,
  type LatchLookup,
} from '../../../lib/chain'
import { CapabilityLedger, LatchAlerts, Ribbon, TrustStrip } from '../components/LatchSignals.tsx'
import { BitGrid, type BitDef } from '../components/series-charts.tsx'
import {
  CALLBACK_GROUPS,
  TOTAL_CALLBACKS,
  bitmapHex,
  hasAlerts,
  latchTone,
  onChainSubline,
  safeHttpUrl,
  shortAddress,
} from '../components/latchModel.ts'
import { dappPath } from '../paths.ts'

/* ============================================================================
   What a held bit lets the Latch DO.

   WHERE THE BIT NUMBERS COME FROM, AND WHY NOT FROM HERE. Not one position is
   typed in this file. `HOOK_CALLBACK_BIT` is generated by
   scripts/sync-registry.mjs from the registry's own `PERM_*` constants and the
   generator FAILS if they disagree with the SDK's `CL_HOOK_FLAGS`; those in
   turn mirror `HOOKS_*_OFFSET` in
   packages/core/src/pool-cl/interfaces/ICLHooks.sol lines 11-24, which is what
   `CLHooks` actually tests `poolKey.parameters` against at every callback site.
   A second table written from memory would drift the day core adds a bit, and
   it would drift silently — the grid would still render, just about a
   different contract than the one on chain.

   WHY THE NOTES SAY THE POWER AND NOT THE NAME. The cell already prints
   `beforeSwapReturnsDelta`. A note reading "returns a delta before the swap"
   is a restatement, and a reader deciding whether to route funds through a
   stranger's pool learns nothing from it. What they need is the consequence:
   the trader pays more than the pool's maths says. Bits 10 and 11 are the two
   that move somebody's money, so they are the two whose notes are written
   hardest.
   ============================================================================ */
const BIT_NOTE: Readonly<Record<HookCallback, string>> = {
  beforeInitialize: 'Can refuse to let a pool open with these parameters.',
  afterInitialize: 'Reads the opening state. Cannot change it.',
  beforeAddLiquidity: 'Can refuse a deposit outright.',
  beforeRemoveLiquidity: 'Can refuse a withdrawal — the funds stay in the pool.',
  afterAddLiquidity: 'Sees a settled deposit. Cannot alter it without bit 12.',
  afterRemoveLiquidity: 'Sees a settled withdrawal. Cannot alter it without bit 13.',
  beforeSwap: 'Can revert the trade, or override the fee charged on it.',
  afterSwap: 'Sees the settled trade. Cannot alter it without bit 11.',
  beforeDonate: 'Can refuse a donation to the pool.',
  afterDonate: 'Sees a settled donation.',
  beforeSwapReturnsDelta:
    'Takes tokens out of the trade before it is priced: the trader pays more, or receives less, than the pool alone would have given. Capped only by HookDeltaExceedsSwapAmount.',
  afterSwapReturnsDelta:
    'Keeps a share of what the trade produced, after pricing. That share leaves with the Latch instead of the trader.',
  afterAddLiquidityReturnsDelta: 'Charges a depositor beyond the liquidity they added.',
  afterRemoveLiquidityReturnsDelta: 'Withholds part of what a withdrawal should have returned.',
}

function bitDefs(names: readonly HookCallback[]): BitDef[] {
  return names.map((name) => ({ bit: HOOK_CALLBACK_BIT[name], name, note: BIT_NOTE[name] }))
}

/* Every result remembers which address it answers for. A result for a previous
   address is simply not shown, so navigating between two Latches never flashes
   the old record under the new URL — and there is no state to reset in an
   effect. */
type Result =
  | { for: string; k: 'error'; message: string }
  | { for: string; k: 'ready'; lookup: LatchLookup }

const ADDRESS_RE = /^0x[a-fA-F0-9]{40}$/

function short(a: string): string {
  return shortAddress(a, 10, 6)
}

function BackLink() {
  return (
    <p className="lx-back">
      <Link to={dappPath('marketplace')}>&larr; All Latches</Link>
    </p>
  )
}

export default function LatchDetail() {
  const { address } = useParams()
  const [result, setResult] = useState<Result | null>(null)
  const chainName = chainNameFor(ACTIVE_CHAIN_ID)
  const registry = DEPLOYMENTS[ACTIVE_CHAIN_ID].registry

  const malformed = !address || !ADDRESS_RE.test(address)

  useEffect(() => {
    if (malformed || !address) return
    let off = false
    readRegisteredLatch(address as `0x${string}`)
      .then((lookup) => !off && setResult({ for: address, k: 'ready', lookup }))
      .catch(
        (e) =>
          !off &&
          setResult({
            for: address,
            k: 'error',
            message: e instanceof Error ? e.message : 'chain unreachable',
          }),
      )
    return () => {
      off = true
    }
  }, [address, malformed])

  if (malformed) {
    return (
      <section className="dapp-card" aria-labelledby="ld-h">
        <div className="dapp-card__head">
          <h2 id="ld-h" className="dapp-card__title">
            That is not a valid address
          </h2>
          <span className="dapp-badge dapp-badge--warn">NOT AN ADDRESS</span>
        </div>
        {/* The second sentence is the one that must survive any trim: without
            it a reader can take "not valid" as a verdict on a Latch. */}
        <p className="live-note">
          A Latch address is <code>0x</code> plus 40 hex characters. Nothing was looked up, so this
          says nothing about any Latch.
        </p>
        <BackLink />
      </section>
    )
  }

  const state = result && result.for === address ? result : null

  if (state === null) {
    return (
      /* The heading names what is being read, so the live region is the whole
         card rather than the sentence under it — announcing "Looking up 0x…"
         without "Reading the registry" leaves out the only word that says what
         kind of answer is coming. */
      <section className="dapp-card" role="status">
        <h2 className="dapp-card__title">Reading the Latch registry…</h2>
        <p className="live-note">
          Looking up {short(address)} on {chainName}.
        </p>
      </section>
    )
  }

  if (state.k === 'error') {
    return (
      <section className="dapp-card">
        <div className="dapp-card__head">
          <h2 className="dapp-card__title">Could not reach the chain</h2>
          <span className="dapp-badge dapp-badge--warn">UNREACHABLE</span>
        </div>
        <p className="live-note live-note--err" role="status">
          {state.message}. A network failure, not a verdict — unreachable is not the same answer as
          &ldquo;not registered&rdquo;.
        </p>
        <BackLink />
      </section>
    )
  }

  if (!state.lookup.found) {
    const { hasCode, checkedAtBlock } = state.lookup
    return (
      <section className="dapp-card" aria-labelledby="ld-nr">
        <div className="dapp-card__head">
          <h2 id="ld-nr" className="dapp-card__title">
            This Latch is not in the registry
          </h2>
          <span className="dapp-badge dapp-badge--warn">NOT REGISTERED</span>
        </div>
        <p className="live-note">
          {hasCode
            ? 'A contract exists at this address, but nobody has ever listed it.'
            : `There is no contract at this address on ${chainName}.`}{' '}
          No verification level, capability class or listing status — because there is no record,
          not because those values are zero. Checked at block {checkedAtBlock.toString()}.
        </p>
        <p className="dapp-note">
          <a
            href={explorerAddress(ACTIVE_CHAIN_ID, address)}
            target="_blank"
            rel="noopener noreferrer"
          >
            View {short(address)} on the block explorer ↗
          </a>
        </p>
        <p className="dapp-note">
          Anyone can list a Latch — registration is permissionless and free.{' '}
          <Link to={dappPath('deploy')}>Deploy a Latch</Link>.
        </p>
        <BackLink />
      </section>
    )
  }

  const h = state.lookup.latch
  const source = safeHttpUrl(h.sourceURI)
  const audit = safeHttpUrl(h.auditURI)
  const held = new Set(h.callbacks)
  const tone = latchTone(h)

  return (
    <div className="lx-detail" data-tone={tone}>
      <BackLink />

      {/* 1 — who it is, the strip, and any warning. */}
      <section className="dapp-card lx-hero" aria-labelledby="ld-name">
        <Ribbon hook={h} />

        <div className="lx-hero__top">
          <span className="dapp-tile lx-hero__icon" aria-hidden="true">
            <span className="dapp-tile__diamond" />
          </span>
          <div className="lx-hero__id">
            <h2 id="ld-name" className="lx-hero__name">
              {h.name || 'Unnamed Latch'}
            </h2>
            <p className="lx-hero__sub" data-risk={h.risk}>
              {onChainSubline(h)}
            </p>
            <p className="lx-hero__by">
              Listed by{' '}
              <a
                href={explorerAddress(h.chainId, h.submitter)}
                target="_blank"
                rel="noopener noreferrer"
              >
                {short(h.submitter)}
              </a>
              <span className="lx-hero__dot" aria-hidden="true">
                ·
              </span>
              <ChainTag chainId={h.chainId} size={14} />
            </p>
          </div>
          <div className="lx-hero__actions">
            <a
              className="dapp-btn dapp-btn--ghost dapp-btn--sm"
              href={explorerAddress(h.chainId, h.address)}
              target="_blank"
              rel="noopener noreferrer"
            >
              Contract ↗
            </a>
            {source && (
              <a
                className="dapp-btn dapp-btn--ghost dapp-btn--sm"
                href={source}
                target="_blank"
                rel="noopener noreferrer"
              >
                Source ↗
              </a>
            )}
            {audit && (
              <a
                className="dapp-btn dapp-btn--ghost dapp-btn--sm"
                href={audit}
                target="_blank"
                rel="noopener noreferrer"
              >
                Audit ↗
              </a>
            )}
          </div>
        </div>

        <TrustStrip hook={h} extended />

        {hasAlerts(h) && (
          <div className="lx-hero__alerts">
            <LatchAlerts hook={h} />
          </div>
        )}
      </section>

      {/* 2 — the un-fakeable section. */}
      <section className="dapp-card lx-section" aria-labelledby="ld-caps">
        <div className="dapp-card__head">
          <h3 id="ld-caps" className="dapp-card__title dapp-card__title--lg">
            Permissions
          </h3>
          <span className="dapp-badge dapp-badge--info tabular">BITMAP {bitmapHex(h)}</span>
        </div>
        <p className="live-note">
          Read from <code>getHooksRegistrationBitmap()</code> on the Latch&rsquo;s own contract. A
          submitter cannot declare a permission their code does not have.
        </p>

        <CapabilityLedger hook={h} detail />

        <div className="lx-matrix">
          <p className="dapp-microlabel dapp-microlabel--tight">
            ALL {TOTAL_CALLBACKS} CALLBACKS · {held.size} HELD
          </p>
          {/* Every bit, held or not, grouped by what holding it lets the Latch
              do. An omitted cell would read as "unknown" rather than as "no",
              which is why `BitGrid` draws the unset ones too. Each cell states
              its own consequence on hover, focus and tap — the reader can walk
              the whole lifecycle from the keyboard without a mouse. */}
          {CALLBACK_GROUPS.map((g) => {
            const n = g.names.filter((name) => held.has(name)).length
            return (
              <section key={g.kind} className="lx-matrix__group" data-kind={g.kind} data-any={n > 0 ? 'yes' : 'no'}>
                <h4 className="lx-matrix__h">
                  <span className="lx-matrix__swatch" aria-hidden="true" />
                  {g.title}
                  <span className="lx-matrix__n tabular">
                    {n} of {g.names.length} held
                  </span>
                </h4>
                <p className="lx-matrix__why">{g.meaning}</p>
                <BitGrid bitmap={h.permissions} bits={bitDefs(g.names)} label={g.title} />
              </section>
            )
          })}

          {/* Bits 14-15 are assigned to nothing in ICLHooks, so no cell above
              can represent them and their absence from the grid would read as
              "clear". Core rejects a pool whose parameters set them, which is
              why this is stated as a fact about the contract rather than left
              to the listing-state alert to imply. */}
          {(h.permissions & PERM.PERM_RESERVED_BITS) !== 0 && (
            <p className="live-note live-note--err" role="status">
              This bitmap also sets reserved bits 14-15, which <code>ICLHooks</code> assigns to no
              callback. No cell above covers them, and core rejects a pool initialised with them.
            </p>
          )}
        </div>
      </section>

      {/* 3 — the submitter's own words, marked as theirs. */}
      <section className="dapp-card lx-section" aria-labelledby="ld-said">
        <div className="dapp-card__head">
          <h3 id="ld-said" className="dapp-card__title dapp-card__title--lg">
            What the submitter says
          </h3>
          <span className="dapp-badge dapp-badge--mute">UNVERIFIED</span>
        </div>
        <p className="live-note">
          Typed by whoever registered the Latch. Not verified, and not a capability claim — the
          section above is.
        </p>
        <blockquote className="lx-quote">
          {h.description || <span className="hx-muted">No description supplied.</span>}
          <cite className="lx-quote__by">
            — {h.name || 'Unnamed Latch'}, as listed by{' '}
            <a
              href={explorerAddress(h.chainId, h.submitter)}
              target="_blank"
              rel="noopener noreferrer"
            >
              {short(h.submitter)} ↗
            </a>
          </cite>
        </blockquote>
      </section>

      {/* 4 — the information table. Each row says where it came from. */}
      <section className="dapp-card lx-section" aria-labelledby="ld-info">
        <h3 id="ld-info" className="dapp-card__title dapp-card__title--lg">
          Information
        </h3>
        <dl className="lx-info">
          <div className="lx-info__row">
            <dt>
              Address <span className="lx-info__src">on chain</span>
            </dt>
            <dd className="lx-info__mono">
              <a
                href={explorerAddress(h.chainId, h.address)}
                target="_blank"
                rel="noopener noreferrer"
              >
                {h.address} ↗
              </a>
            </dd>
          </div>
          <div className="lx-info__row">
            <dt>
              Chain <span className="lx-info__src">on chain</span>
            </dt>
            <dd>
              <ChainTag chainId={h.chainId} size={14} />
            </dd>
          </div>
          <div className="lx-info__row">
            <dt>
              Registry <span className="lx-info__src">on chain</span>
            </dt>
            <dd className="lx-info__mono">
              <a
                href={explorerAddress(ACTIVE_CHAIN_ID, registry)}
                target="_blank"
                rel="noopener noreferrer"
              >
                LatchRegistry {shortAddress(registry)} ↗
              </a>
            </dd>
          </div>
          <div className="lx-info__row">
            <dt>
              Submitter <span className="lx-info__src">on chain</span>
            </dt>
            <dd className="lx-info__mono">
              <a
                href={explorerAddress(h.chainId, h.submitter)}
                target="_blank"
                rel="noopener noreferrer"
              >
                {h.submitter} ↗
              </a>
            </dd>
          </div>
          <div className="lx-info__row">
            <dt>
              Bitmap <span className="lx-info__src">on chain</span>
            </dt>
            <dd className="lx-info__mono tabular">
              {bitmapHex(h)} · {held.size} of {TOTAL_CALLBACKS} callbacks
            </dd>
          </div>
          <div className="lx-info__row">
            <dt>
              Source <span className="lx-info__src lx-info__src--claim">submitter&rsquo;s link</span>
            </dt>
            <dd className="lx-info__mono">
              {source ? (
                <a href={source} target="_blank" rel="noopener noreferrer">
                  {source} ↗
                </a>
              ) : (
                <span className="hx-muted">{h.sourceURI || 'none given'}</span>
              )}
            </dd>
          </div>
          <div className="lx-info__row">
            <dt>
              Audit <span className="lx-info__src lx-info__src--claim">submitter&rsquo;s link</span>
            </dt>
            <dd className="lx-info__mono">
              {audit ? (
                <a href={audit} target="_blank" rel="noopener noreferrer">
                  {audit} ↗
                </a>
              ) : (
                <span className="hx-muted">{h.auditURI || 'none given'}</span>
              )}
            </dd>
          </div>
          <div className="lx-info__row">
            <dt>Public record</dt>
            <dd className="lx-info__mono">
              <a href={`/verify/${h.address}`} target="_blank" rel="noopener noreferrer">
                /verify/{shortAddress(h.address)} ↗
              </a>
              <span className="lx-info__aside"> — the same record, no wallet, no app.</span>
            </dd>
          </div>
        </dl>
        <p className="dapp-note lx-section__note">
          A link marked as the submitter&rsquo;s is a claim, not a verification — follow it and
          read what is on the other end.
        </p>
        <BackLink />
      </section>
    </div>
  )
}
